import type { Metadata } from "next";
import { Roboto} from 'next/font/google'
import "./globals.css";

import logoImg from '../assets/logo.svg'
import Image from "next/image";


const roboto = Roboto({
  subsets: ['latin'],
  variable: '--font-roboto',
  weight: ['400','700'],
})



export const metadata: Metadata = {
  title: "Ignite Shop",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased ${roboto.variable}`}
      >
        <div className="flex flex-col items-start justify-center min-h-screen">
          <header className="py-8 w-full max-w-6xl mx-auto">
            <Image src={logoImg} alt="" />
          </header>
          {children}
        </div>
      </body>
    </html>
  );
}
